chore: fix all explicit output redirections

diff --git a/.local/script/files-search-replace b/.local/script/files-search-replace
--- a/.local/script/files-search-replace
+++ b/.local/script/files-search-replace
@@ -3,12 +3,12 @@
 set -Eeuo pipefail
 
 command git rev-parse HEAD &>/dev/null || {
-	echo "Unsafe to run outside of a git repo" >/dev/stderr
+	echo "Unsafe to run outside of a git repo" >&2
 	exit 1
 }
 
 if [[ "$#" -lt 1 ]]; then
-	echo "Please pass a substitute regex s/// or s{}{}" >/dev/stderr
+	echo "Please pass a substitute regex s/// or s{}{}" >&2
 	exit 1
 fi
 
@@ -21,7 +21,7 @@ if [[ "$regex" =~ ^s/ ]]; then
 elif [[ "$regex" =~ ^s\{ ]]; then
 	search=$(echo "$regex" | grep -o -P '(?<=s{)(.*?)(?=}{)')
 else
-	echo "Invalid regex: '$regex'" >/dev/stderr
+	echo "Invalid regex: '$regex'" >&2
 	exit 1
 fi
 
diff --git a/.local/script/fzf-git-file-show-history b/.local/script/fzf-git-file-show-history
--- a/.local/script/fzf-git-file-show-history
+++ b/.local/script/fzf-git-file-show-history
@@ -7,12 +7,12 @@ git-in-repo || exit 95
 PTH="${*: -1}"
 
 if [[ -z "$PTH" || "$PTH" == '--' || "$PTH" == "$0" ]]; then
-	echo "Provide relative path to file" > /dev/stderr
+	echo "Provide relative path to file" >&2
 	exit 1
 fi
 
 # if [[ ! -e "$PTH" ]]; then
-# 	echo "Path not found: $PTH" > /dev/stderr
+# 	echo "Path not found: $PTH" >&2
 # 	exit 2
 # fi
 
diff --git a/.local/script/gl-commit-create-from-stage b/.local/script/gl-commit-create-from-stage
--- a/.local/script/gl-commit-create-from-stage
+++ b/.local/script/gl-commit-create-from-stage
@@ -15,11 +15,11 @@ while ((1)); do
 	esac
 done
 
-[[ -z "${message:-}"   ]] && { echo "error: message is required" >/dev/stderr; exit 1; }
+[[ -z "${message:-}"   ]] && { echo "error: message is required" >&2; exit 1; }
 
 source "$HOME/.local/lib/shell/gitlab.bash"
 
-[[ -z "${GL_BRANCH:-}" ]] && { echo "error: branch is required"  >/dev/stderr; exit 1; }
+[[ -z "${GL_BRANCH:-}" ]] && { echo "error: branch is required"  >&2; exit 1; }
 
 gl-redefine-vars
 
@@ -29,7 +29,7 @@ else
 	pushd "$GL_ROOT" >/dev/null
 
 	if ! changes="$(git status --porcelain | grep -P '^A|^D|^M')"; then
-		echo 'nothing to do' >/dev/stderr
+		echo 'nothing to do' >&2
 		exit 0
 	fi
 
@@ -45,7 +45,7 @@ else
 	if actions="$(echo "$changes" \
 		| xargs -rn2 bash -c '
 			set -e;
-			[[ "$0" == "D" || -r "$1" ]] || { echo file not found: "$1" >/dev/stderr; exit 2; }
+			[[ "$0" == "D" || -r "$1" ]] || { echo file not found: "$1" >&2; exit 2; }
 			pth="$1"
 			[[ "$0" == "D" ]] && { pth=/dev/null; }
 			jq -nc --arg a "$0" --rawfile content "$pth" --arg file "$1" '\'"$jq_convert"\'
diff --git a/.local/script/tsv2mysql-insert b/.local/script/tsv2mysql-insert
--- a/.local/script/tsv2mysql-insert
+++ b/.local/script/tsv2mysql-insert
@@ -15,7 +15,7 @@ while [ : ]; do
 	esac
 done
 
-[[ -z "${table:-}" ]] && { echo "error: table is required" >/dev/stderr; exit 1; }
+[[ -z "${table:-}" ]] && { echo "error: table is required" >&2; exit 1; }
 
 cat "$@" \
 	| jq --null-input --raw-input --raw-output --unbuffered --arg table "$table" --arg update "${update:-}" '
