chore: misc updates

diff --git a/.local/script/gl-mr-create b/.local/script/gl-mr-create
--- a/.local/script/gl-mr-create
+++ b/.local/script/gl-mr-create
@@ -2,14 +2,13 @@
 
 set -Eeuo pipefail
 
-args="$(getopt --name="$0" --options 'h:p:m:s:t:' --longoptions 'host:,project:,message:,source:,target:' -- "$@")"
+args=$(getopt --name="$0" --options 'h:p:m:s:t:' --longoptions 'host:,project:,message:,source:,target:' -- "$@")
 eval set -- "$args"
 
-# shellcheck disable=SC2078
-while [ : ]; do
+while ((1)); do
 	case "$1" in
-		-h | --host) HOST="$2"; shift 2 ;;
-		-p | --project) PROJECT="$2"; shift 2 ;;
+		-h | --host) GL_HOST="$2"; shift 2 ;;
+		-p | --project) GL_PROJECT="$2"; shift 2 ;;
 		-m | --message) message="$2"; shift 2 ;;
 		-s | --source) source="$2"; shift 2 ;;
 		-t | --target) target="$2"; shift 2 ;;
@@ -17,22 +16,11 @@ while [ : ]; do
 	esac
 done
 
-source "$HOME/.local/lib/shell/gitlab.bash"
-
-[[ -z "${target:-}" ]]  && { echo "target is required"; exit 1; }
 [[ -z "${message:-}" ]] && { echo "message is required"; exit 1; }
 [[ -z "${source:-}" ]]  && { echo "source is required"; exit 1; }
+[[ -z "${target:-}" ]]  && { echo "target is required"; exit 1; }
 
-# https://docs.gitlab.com/ee/api/merge_requests.html#create-mr
+source "$HOME/.local/lib/shell/gitlab.bash"
+gl-redefine-vars
 
-http_post_command=(
-	xhs
-	"${HOST}/$API/projects/$(url_encode "$PROJECT")/merge_requests"
-	"${COMMON_XH_OPTIONS[@]}"
-	"source_branch=$source"
-	"target_branch=$target"
-	"title=$message"
-	"remove_source_branch=true"
-)
-
-exec "${http_post_command[@]}"
+gl-mr-create "$GL_PROJECT" "$message" "$source" "$target"
