chore: misc updates

diff --git a/.local/script/mkbash b/.local/script/mkbash
--- a/.local/script/mkbash
+++ b/.local/script/mkbash
@@ -2,14 +2,14 @@
 
 set -Eeuo pipefail
 
-[[ -r "$1" ]] && exit 1
+[[ -r "$1" ]] || {
+	{
+		echo '#!/usr/bin/env bash'
+		echo
+		echo 'set -Eeuo pipefail'
+	} >> "$1"
 
-{
-	echo '#!/usr/bin/env bash'
-	echo
-	echo 'set -Eeuo pipefail'
-} >> "$1"
-
-chmod a+x "$1"
+	chmod a+x "$1"
+}
 
 "${VISUAL:-vim}" "$1"
